### ISSUE TITLE
Travis CI Failing

### ISSUE THREAD

**Issue by martinGerez** [rubycdp/cuprite#154]
Hi, I have been using Cuprite for a while, and is working fine in the local environment. But I can't get it to work on Travis CI.

I can't find any documentation or post or anything about the build config.
Each system test fails with the same error:
```
Ferrum::NoSuchTargetError:
            Ferrum::NoSuchTargetError
``` 

My `.travis.yml`:
```
env:
  global:
    - CC_TEST_REPORTER_ID=MY_TEST_REPORTER_ID
    - BROWSER_PATH=/usr/bin/google-chrome
dist: trusty
language: ruby
cache:
  - bundler
  - yarn
addons:
  postgresql: "9.4"
  chrome: stable
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - gem install bundler
  - bundle install --jobs=3 --retry=3
  - yarn
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:schema:load
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
```
Have you any advice or documentation to get it to work? Thanks a lot!
