### ISSUE TITLE
Ferrum::PendingConnectionsError when running on Github Actions

### ISSUE THREAD

**Issue by swanson** [rubycdp/cuprite#183]
I've got a test suite with one test that is working great locally (headless or non-headless) but when I try to run it on github actions, I get `Ferrum::PendingConnectionsError` errors:

```
Ferrum::PendingConnectionsError: Request to http://127.0.0.1:39001/login/1380151900b91f44e88b6d0c2bec37f4 reached server, but there are still pending connections: http://127.0.0.1:39001/plans
```

I've tried lots of combinations of options/timeouts/settings and I don't believe there is anything in the app that is slow/fails to load. I tried the Docker `'no-sandbox'` options, `process_timeout`, `timeout`, etc

What is the best way to debug?

My Github action workflow:

```yaml
system_tests:
    name: System Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
    env:
      STRIPE_ENDPOINT_SECRET: ${{secrets.STRIPE_ENDPOINT_SECRET}}
      STRIPE_PUBLISHABLE_KEY: ${{secrets.STRIPE_PUBLISHABLE_KEY}}
      STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.16.2
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        run: |
          bin/rails db:setup

      - name: Run tests
        run: bin/rails test:system
```

```ruby
require "capybara/cuprite"

Capybara.register_driver :cuprite do |app|
  Capybara::Cuprite::Driver.new(app,
    window_size: [1400, 1200],
    headless: ENV["CI"],
    timeout: 10)
end
```

```ruby
require "application_system_test_case"

class SmokeTest < ApplicationSystemTestCase
  test "getting started" do
    visit confirm_login_token_path(token: sessions(:test_user).token)
    visit root_url # traceback references this line

   # root_url => /plans as shown in the error

    # rest of the test
  end
end
```
