### ISSUE TITLE
How to use Cuprite with a remote browser (browserless/chrome) 

### ISSUE THREAD

**Issue by SirMishaa** [rubycdp/cuprite#221]
Hello ! 

In my work, I'd like to have a remote chrome browser using https://hub.docker.com/r/browserless/chrome
```yml
  app:
    build:
      context: .
      # The target is really important here. It specifies which stage of the Dockerfile to use.
      target: dev
      args:
        BUILDING_ENV: development
    image: aaaaaaa
    entrypoint: ./entrypoints/puma-entrypoint.sh
    volumes:
      - .:/opt/app
      - gem_cache:/usr/local/bundle/gems
      - /opt/app/node_modules
    env_file:
      - .env.dev
      - .env
    environment:
      - VITE_RUBY_HOST=vite
    ports:
      - '${APP_PORT:-8080}:3000'
    depends_on:
      - postgres
      - redis

  chrome:
    # Currently, Apple M1 is only supported in unnumbered "latest" versions.
    # See https://github.com/browserless/chrome/issues/1393
    image: browserless/chrome:latest
    ports:
      - "3333:3333"
    # Mount application source code to support file uploading
    # (otherwise Chrome won't be able to find files).
    # NOTE: Make sure you use absolute paths in `#attach_file`.
    volumes:
      - .:/app:cached
    environment:
      # By default, it uses 3000, which is typically used by Rails.
      PORT: 3333
      # Set connection timeout to avoid timeout exception during debugging
      # https://docs.browserless.io/docs/docker.html#connection-timeout
      CONNECTION_TIMEOUT: 600000
```

It seems to run, we got messages when running tests 
![image](https://user-images.githubusercontent.com/42717232/209172220-a4a90252-f347-4a8b-af64-b7f9dd147e8d.png)

But unfortunately, all tests are failing 
![image](https://user-images.githubusercontent.com/42717232/209172416-e2a6d2e2-921d-4d16-855c-b49659f72653.png)

I was wondering if you have ever successfully implemented this kind of thing (I was inspired by that article https://evilmartians.com/chronicles/system-of-a-test-setting-up-end-to-end-rails-testing) ? The goal is also to be able to see the browser interface via an X server, that's why we use https://hub.docker.com/r/browserless/chrome

Thanks a lot!

**Comment by n1xn** [comment]
**docker-compose.yml**
```
...
  browserless:
    image: browserless/chrome:latest
    container_name: ${COMPOSE_PROJECT_NAME}_browserless
    restart: always
    environment:
      - PORT=4000
    ports:
      - '4000:4000'
```

**.env**
```
BROWSERLESS_URL=http://localhost:4000/
```

**usage**
```
@browser = Ferrum::Browser.new(url: ENV.fetch('BROWSERLESS_URL', nil))
```
